### ISSUE TITLE
Snapista installation

### ISSUE THREAD

**Issue by mbm87** [snap-contrib/snapista#11]
Good morning.

I cannot install Snapista in any way. I have created several conda environments with different python versions but whenever I type conda install -c terradue snapista in the terminal, a problem with the python version occurs. As I said before, I have tried several Python versions according to the message which pops up on my screen, but I have not been able to install it. I attach two screenshots.

Best regards,
Mario

With Python 3.7:
![capturasnapista](https://user-images.githubusercontent.com/79213631/120784923-e53ac900-c52c-11eb-8b3d-8eb08a98707a.png)

With Python3.5:

![snapista2](https://user-images.githubusercontent.com/79213631/120785976-fc2deb00-c52d-11eb-8cb5-8dfe165685e7.png)

**Comment by mbm87** [comment]
And my conda environment: 

![environment](https://user-images.githubusercontent.com/79213631/120785225-3c409e00-c52d-11eb-8948-7a9b8a032d4d.png)

**Comment by fabricebrito** [comment]
@mbm87 I can't see the images posted. I suspect there's still an issue with the java conda dependency. I'll check and try to fix asap

**Comment by mbm87** [comment]
> @mbm87 I can't see the images posted. I suspect there's still an issue with the java conda dependency. I'll check and try to fix asap

Hi Fabrice, I attach you the text:

With Python 3.5.6: 

(snapenv) mario@DebianE:~$ conda install -c terradue snapista
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                    

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - snapista -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

With Python 3.7.10:

(snapenv) mario@DebianE:~$ conda install -c terradue snapista
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                    

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - snapista -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by fabricebrito** [comment]
@mbm87 snapista works with python 3.7, 3.8 and 3.9. 

Can you try with:

```console
conda install -n base mamba
mamba create -n test_snap -c terradue -c conda-forge snapista python=3.7
``` 
That install mamba in your base environment which is faster and creates an env with python 3.7

**Comment by mbm87** [comment]
Thx Fabrice I was finally able to install following your commans. Many thanks.
