### ISSUE TITLE
Are there alternative installation options?

### ISSUE THREAD

**Issue by iod-ine** [snap-contrib/snapista#17]
Good afternoon!

Are there alternative installation options for snapista? I have tried installing it on two separate machines with no success. Here is what I tried:

1. On my personal macOS machine, conda doesn't find the package at all. So instead I tried cloning the repository and installing it manually, but there is no requirements file. I tried figuring out the requirements one by one by failing to import snapista in the Python console, and the second requirement is snappy, which is super unexpected because I thought that snapista is a replacement for non-pythonic and performance degrading snappy. At this point I gave up, at least for now, to install it on this machine.
2. On my Ubuntu workstation, conda did find snapista, but even an environment that I just used for snappy was for some reason incompatible. I tried creating a separate environment for just snapista, and was very surprised to see that it was installing a brand new version of snap itself, which is weird, because I obviously already have a latest install and just need a Python wrapper for gpt. I installed it anyway, and it even kind of worked for a bit: I managed to play around with different operators. But the moment I tried to initialize a Graph object, an exception was raised that gpt could not be found. Which is also super weird, because I now have two gpts: one that I had before and one that I assume was installed with snapista into a conda environment. The original gpt is definitely on my PATH, so I am lost.

Can you please help me install snapista?

**Comment by geovicco** [comment]
Having the exact same issue where I have gpt specified in my OS Path, but initializing a Graph doesn't work. The function get_gpt_cmd() must be tweaked.

**Comment by fabricebrito** [comment]
Snapista is a conda package so the only way to install it is via conda or mamba. 
For Windows and MacOs users see alternative approaches provided in https://snap-contrib.github.io/snapista/installation.html

Snappy is used to support the creation of the graphs and in particular to get the operators parameters. It is not used to process the graph.
