### ISSUE TITLE
Expected speed for SAR calibration

### ISSUE THREAD

**Issue by SimJeg** [snap-contrib/snapista#18]
Hello !

First thank you for developing and maintaining this snapista package. To install the package I had to first run `conda install -c terradue -c conda-forge snap=8.0.0`, it may be useful to precise it in the README.

I am applying the operations listed below on Sentinel-1 data (~1.5GB)  and it took ~10mins on a machine with 8 CPUs. Is it what I sould expect ? 

- Manifest name: S1A_IW_GRDH_1SDV_20220113T015151_20220113T015216_041436_04ED43_BAD7.SAFE
- Operations
   - Read
   - Apply-Orbit-File"
   - Remove-GRD-Border-Noise
   - Calibration
   - Write

I am currently adding the Terrain-Flattening and Terrain-Correction to see how long it takes

Thanks

**Comment by SimJeg** [comment]
There may be a problem on my side as running the following code takes 6 minutes : 

```
import os
from snapista import Graph, Operator

path_to_manifest = '/data/sentinel1/S1A_IW_GRDH_1SDV_20220113T015151_20220113T015216_041436_04ED43_BAD7.SAFE'

g = Graph()

g.add_node(
    operator=Operator(
        "Read",
        formatName="SENTINEL-1",
        file=path_to_manifest,
    ),
    node_id="read",
)
g.add_node(
    operator=Operator("Write", file='output.tif',
                      formatName="GeoTIFF-BigTIFF"),
    node_id="write",
    source="read",
)

g.run()
```

**Comment by fabricebrito** [comment]
Hello @SimJeg, 
You can customize the performance of `gpt`, see https://github.com/snap-contrib/snapista/blob/master/src/snapista/graph.py#L378
